apiVersion: v1
kind: ServiceAccount
metadata:
  name: pods-listener
  namespace: todoapp

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role
  namespace: todoapp
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-listener-binding
  namespace: todoapp
subjects:
  - kind: ServiceAccount
    name: pods-listener
roleRef:
  kind: Role
  name: pod-listener
  apiGroup: rbac.authorization.k8s.io